name: livecodes

on: [pull_request]

jobs:
  build_and_prepare:
    runs-on: ubuntu-latest
    name: Generate Playgrounds
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and generate
        uses: hatemhosny/gh-action-example@main
        with:
          install-command: "npm install"
          build-command: "npm run build"
          base-url: "https://gh-action-consumer-git-{{LC::REF}}-hatem-hosnys-projects.vercel.app/"
