on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world action step
        id: hello
        uses: hatemhosny/gh-action-example@main
        with:
          who-to-greet: "Mona the Octocat"
          install-command: "npm install"
          build-command: "npm run build"
          file-list: "dist/index.txt"
          GITHUB_TOKEN: ${{ github.token }}

      - name: Comment PR with execution number
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
          comment_tag: execution

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
